python detection.py -name No_entry/NoEntry0.bmp
python detection.py -name No_entry/NoEntry1.bmp
python detection.py -name No_entry/NoEntry2.bmp
python detection.py -name No_entry/NoEntry3.bmp
python detection.py -name No_entry/NoEntry4.bmp
python detection.py -name No_entry/NoEntry5.bmp
python detection.py -name No_entry/NoEntry6.bmp
python detection.py -name No_entry/NoEntry7.bmp
python detection.py -name No_entry/NoEntry8.bmp
python detection.py -name No_entry/NoEntry9.bmp
python detection.py -name No_entry/NoEntry10.bmp
python detection.py -name No_entry/NoEntry11.bmp
python detection.py -name No_entry/NoEntry12.bmp
python detection.py -name No_entry/NoEntry13.bmp
python detection.py -name No_entry/NoEntry14.bmp
python detection.py -name No_entry/NoEntry15.bmp
